---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: welldone-gatsby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welldone-gatsby
  template:
    metadata:
      labels:
        app: welldone-gatsby
    spec:
      containers:
        - name: welldone-gatsby
          image: gcr.io/welldone-deployments/welldone-gatsby:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: welldone-gatsby-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 80
  selector:
    app: welldone-gatsby
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: welldone-gatsby-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts:
        - "*.welldone.software"
  rules:
    - host: welldone.software
      http:
        paths:
          - path: /
            backend:
              serviceName: welldone-gatsby-service
              servicePort: 9000
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: welldone-gatsby-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts:
        - "*.welldone-software.com"
  rules:
    - host: welldone.software
      http:
        paths:
          - path: /
            backend:
              serviceName: welldone-gatsby-service
              servicePort: 9000
